name = "FriendPack"
author = "Sol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6ad29e1600f392d49675e7516aebd0ff5f964988c04d05635f0a8d74b63a28e"

[versions]
fabric = "0.16.14"
minecraft = "1.19.2"
