name = "FriendPack"
author = "Sol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "496550cec0a28a510b24525e99b1adb56f2e43b05b3ed3deb05d60339f71cb3a"

[versions]
fabric = "0.16.14"
minecraft = "1.19.2"
