name = "FriendPack"
author = "Sol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f618015eac3f424be6ef2468a5caa3f1fe22703655279c8340256b788bfe474b"

[versions]
fabric = "0.16.14"
minecraft = "1.19.2"
